framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            worker: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: worker
                    exchange:
                        name: worker
                    queues:
                        messages_worker: ~
            front: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: front
                    exchange:
                        name: front
                    queues:
                        messages_front: ~
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\InstanceActionMessage': worker
            'App\Message\InstanceStateMessage': front
